Repository AY2223S2-CS2103T-W12-2/tp, pull requests merged in 2023-04, with the labels that each got.

#206 Fix undo and redo bug
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandHistory.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
Labels: type.Bug, priority.High

#207 Fix some UG bugs and help link
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug, priority.High

#208 Fix UG bugs on images
  docs/UserGuide.md
  docs/images/user-guide/filter_after.jpg
  docs/images/user-guide/filter_before.jpg
  docs/images/user-guide/remark_during.jpg
  docs/images/user-guide/sample_GUI.jpg
Labels: type.Bug, priority.High, type.docs

#209 Fix bug duplicate persons/phone/tele when empty
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug, priority.High

#212 Fix #210
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/ResultPersonCard.java
  src/main/java/seedu/address/ui/ResultPersonListPanel.java
Labels: type.Bug

#211 Fix Telegram regex
  docs/UserGuide.md
  docs/images/user-guide/help_popup.jpg
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/model/person/TelegramTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#213 Update PPP
  docs/team/wendy0107.md
Labels: priority.High, type.docs

#219 Fix UG formatting
  docs/UserGuide.md
Labels: type.Bug, priority.High, type.docs

#220 Fix margins of more alert `div` in UG
  docs/UserGuide.md
Labels: type.Bug, priority.Low, type.docs

#225 Fix all checkstyle warnings in `main` except missing java docs warnings
  src/main/java/seedu/address/logic/commands/AutocompleteEngine.java
  src/main/java/seedu/address/logic/commands/CommandHistory.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/predicates/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/logic/parser/predicates/FullMatchKeywordsPredicate.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
Labels: type.Task

#226 Fix checkstyles docs
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/wendy0107.md
Labels: type.Task, type.docs

#227 Fix checkstyles test
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/TelegramTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task

#236 Fix autocompletion misaligning when command input is very long
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug

#230 Fix JavaFX API warnings
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/RemarkWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/ResultPersonCard.fxml
  src/main/resources/view/ResultPersonListPanel.fxml
  src/main/resources/view/StatusBarFooter.fxml
  src/test/resources/view/UiPartTest/validFile.fxml
Labels: type.Bug, priority.Low

#237 Add Javadocs for Undo Redo and show bugs not fixed
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/CommandHistory.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultPersonCard.java
Labels: type.Bug, type.docs

#228 Fix inability to differentiate "removal of remarks" from "opening remark box"
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.High

#246 Fix VSCode's test feat. not working
  build.gradle
Labels: type.Bug, type.Task

#247 Move `CommandHistory` from `LogicManager` to `ModelManager`
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/CommandHistory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: type.Task

#244 Revert unique Telegram/phone/case-insensitive-name feature
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Task

#249 Fix 'AddCommand' usage message
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: type.Bug

#252 Fix `remark` command's error message
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
Labels: type.Bug, priority.Medium

#254 Fix `edit` command error messages
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: type.Bug, priority.Low

#256 Refactor command usage msg
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/logic/parser/Prefix.java
Labels: type.Task

#257 Fix `show` command error messages
  src/main/java/seedu/address/logic/parser/ShowRemarkCommandParser.java
Labels: type.Bug, priority.Low

#258 Refactor 'ShowRemarkCommand::parse'
  src/main/java/seedu/address/logic/parser/ShowRemarkCommandParser.java
Labels: type.Task

#259 Refactor invalid index msg by moving it into `ParserUtil::parseIndex`
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ShowRemarkCommandParser.java
Labels: type.Task

#262 Fix deletecommandtest, clearcommandtest and edit command parser
  src/main/java/seedu/address/model/person/Education.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/tag/ModuleTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug

#265 Move `CommandHistory` functionality into `VersionedAddressBook`
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/model/CommandHistory.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Bug

#243 Update UG 1.4
  docs/UserGuide.md
  docs/images/user-guide/mainwindow-components.jpg
  docs/images/user-guide/resize-window.jpg
  docs/img.png
Labels: type.docs

#268 Replace author-tag with adapted-comment in `AutocompleteEngine`
  src/main/java/seedu/address/logic/commands/AutocompleteEngine.java
Labels: type.Task

#270 Revert "Update DG with planned enhancements"
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/UserGuide_BACKUP_559.md
  docs/UserGuide_BASE_559.md
  docs/UserGuide_LOCAL_559.md
  docs/UserGuide_REMOTE_559.md
  docs/img_1.png
  docs/img_2.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/logic/parser/ShowRemarkCommandParser.java
  src/main/java/seedu/address/model/CommandHistory.java
  src/main/java/seedu/address/model/person/Education.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, priority.High, type.docs

#271 Update DG with planned enhancements (fixed)
  docs/DeveloperGuide.md
Labels: type.docs

#274 Change thrown exceptions `AutocompleteEngine`
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AutocompleteEngine.java
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Task

#266 Fix delete command duplicate index
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: type.Bug

#275 Add autocomplete tests
  src/main/java/seedu/address/logic/commands/AutocompleteEngine.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AutocompleteEngineTest.java
  src/test/java/seedu/address/testutil/ModelStub.java
Labels: type.Task

#277 Fix ug param
  docs/UserGuide.md
Labels: type.Bug, type.docs

#276 Update DG, and fix some minor UG errors
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram2.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/RedoSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/DeleteSequenceDiagram2.png
  docs/images/EditSequenceDiagram.png
  docs/images/FilterSequenceDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/RedoSequenceDiagram.png
Labels: type.docs

#280 Remove `r/` prefix for 'remark' in UG & DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug

#282 Fix heading levels in DG
  docs/DeveloperGuide.md
Labels: type.Bug, type.docs

#283 Fix inconsistent note tip
  docs/UserGuide.md
Labels: type.Bug, type.docs

#285 Fix inconsistent note tip fixed (fixed)
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, type.docs

#286 Fix 'Notes about the command format' box in UG
  docs/UserGuide.md
Labels: type.Bug, type.docs

#287 Update ug autocomplete
  docs/UserGuide.md
  docs/images/user-guide/autocomplete_heuristics.jpg
Labels: type.docs

#288 Update delete section with requiring unique indexes in UG
  docs/UserGuide.md
Labels: type.docs

#292 Add autocomplete implementation in DG
  docs/DeveloperGuide.md
  docs/diagrams/AutocompleteSequenceDiagram.puml
  docs/diagrams/SuggestionSequenceDiagram.puml
  docs/images/AutocompleteSequenceDiagram.png
  docs/images/SuggestionSequenceDiagram.png
Labels: type.docs

#293 Tweak formatting for autocomplete in DG
  docs/DeveloperGuide.md
Labels: type.docs

#291 Update DG with missing sections in find/filter
  docs/DeveloperGuide.md
Labels: type.docs

#294 Fix textfield undo not working with autocompletion
  src/main/java/seedu/address/ui/CommandBox.java
Labels: type.Bug

#295 Fix typo in `AutocompleteEngine` javadoc
  src/main/java/seedu/address/logic/commands/AutocompleteEngine.java
Labels: type.Bug, type.docs

#296 Remove Ui object in autocomplete sequence diagrams
  docs/diagrams/AutocompleteSequenceDiagram.puml
  docs/diagrams/SuggestionSequenceDiagram.puml
  docs/images/AutocompleteSequenceDiagram.png
  docs/images/SuggestionSequenceDiagram.png
Labels: type.docs

#297 Fix inablity to delete edu via edit
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug

#298 Remove proposed sort feat in DG
  docs/DeveloperGuide.md
Labels: type.docs

#305 Edit format for Find and Filter in the UG
  docs/UserGuide.md
Labels: type.docs

#308 Update dg seq diag
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/RemarkSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/EditSequenceDiagram.png
  docs/images/RemarkSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: type.docs

#310 Update acknowledge dg
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/parser/Prefix.java
Labels: type.docs

#300 Edit the Remark section for the DG
  docs/DeveloperGuide.md
Labels: type.docs

#311 Change DG TOC to unordered
  docs/DeveloperGuide.md
Labels: type.docs

#314 Refactor suggest command in `AutocompleteEngine`
  src/main/java/seedu/address/logic/commands/AutocompleteEngine.java
Labels: type.Task

#313 Fix edit parsing 'r/' prefix
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
Labels: type.Bug

#334 2101 ug fixes
  docs/UserGuide.md
Labels: type.docs
