Repository AY2223S2-CS2103T-W12-2/tp, pull requests merged in 2023-03, with the labels that each got.

#56 Use `Optional` in the remark field
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Task

#58 Fix `Person::toString` display empty fields
  src/main/java/seedu/address/model/person/Person.java
Labels: type.Bug

#54 Subject tag
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Subject.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSubject.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement

#73 Fix empty string fields in JSON savefile
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Education.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Bug

#66 Update developer guide with v1.2
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StudentClassDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/StudentClassDiagram.png
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Remark.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#76 Add "Add a new student" use case to DG
  docs/DeveloperGuide.md
Labels: type.docs

#78 Enable assertions for Gradle
  build.gradle
Labels: type.Task

#87 Fix prefix format in implementation and user stories
  docs/DeveloperGuide.md
Labels: type.docs

#89 Update UG
  docs/UserGuide.md
  docs/images/user-guide/add_after.jpg
  docs/images/user-guide/add_before.jpg
  docs/images/user-guide/delete_after.jpg
  docs/images/user-guide/delete_before.jpg
  docs/images/user-guide/edit_after.jpg
  docs/images/user-guide/edit_before.jpg
  docs/images/user-guide/find_after.jpg
  docs/images/user-guide/find_before.jpg
  docs/images/user-guide/help_popup.jpg
  docs/images/user-guide/remark_after.jpg
  docs/images/user-guide/remark_before.jpg
  docs/images/user-guide/show_after.jpg
  docs/images/user-guide/show_before.jpg
Labels: type.docs

#90 Fix table of contents in UG
  docs/UserGuide.md
Labels: type.Bug, type.docs

#91 Fix UG formatting
  docs/UserGuide.md
Labels: type.Bug, type.docs

#92 Fix the before image of 'find' cmd in UG
  docs/images/user-guide/find_before.jpg
Labels: type.Bug, type.docs

#93 Increase heading lvls of sections under 'Implementation' in DG
  docs/DeveloperGuide.md
Labels: type.Bug, type.docs

#94 Update Ui for show command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultPersonCard.java
  src/main/java/seedu/address/ui/ResultPersonListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/ResultPersonCard.fxml
  src/main/resources/view/ResultPersonListPanel.fxml
Labels: type.Task

#95 Update DG with UML diagrams for delete, find and list
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram2.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/images/DeleteSequenceDiagram2.png
  docs/images/FindSequenceDiagram.png
  docs/images/ListSequenceDiagram.png
Labels: type.docs

#99 Update developer guide v1.2
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/DeleteSequenceDiagram2.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/DeleteSequenceDiagram2.png
  docs/images/UiClassDiagram.png
Labels: type.docs

#106 Improve navigability, add parameters table and other miscellaneous info
  docs/UserGuide.md
Labels: type.docs

#114 (week 11) Update DG
  docs/DeveloperGuide.md
Labels: type.Bug, type.docs

#115 Fix formating of user stories priority legend
  docs/DeveloperGuide.md
Labels: type.Bug, type.docs

#121 Add ctrl + Z handler to exit remark window
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/ui/RemarkWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/teacher.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/RemarkWindow.fxml
Labels: type.Enhancement, priority.High

#123 Updated find command to remove space after prefix
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/predicates/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/logic/parser/predicates/FullMatchKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: type.Enhancement

#128 Fix syntax error
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: type.Bug

#130 Add autocompletion feature
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AutocompleteEngine.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/Prefix.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
Labels: type.Enhancement

#133 Fix some checkstyle warnings
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/FullNamePredicate.java
  src/main/java/seedu/address/ui/ResultPersonCard.java
Labels: type.Bug

#120 Undo redo feature
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/CommandHistory.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ShowRemarkCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
Labels: type.Story, priority.High, type.Task

#134 Rename subject to module
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/StudentClassDiagram.puml
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/predicates/FullMatchKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Module.java
  src/main/java/seedu/address/model/tag/Subject.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedSubject.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/ResultPersonCard.java
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task

#136 Autocomplete modules and educations fields
  src/main/java/seedu/address/logic/commands/AutocompleteEngine.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
Labels: type.Enhancement

#138 Add sample remark data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Low

#142 Fix bugs and compile error
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AutocompleteEngine.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Bug, priority.High

#143 Fix 141
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/predicates/ContainsKeywordsPredicate.java
  src/main/java/seedu/address/logic/parser/predicates/FullMatchKeywordsPredicate.java
Labels: type.Bug, priority.High

#179 Fix sample data bug
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: type.Bug, priority.High

#189 Fix bug of `show` not working for newly added students and removed some comments from telegram class
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Telegram.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.High
